### PR TITLE
CB-286: Add tests for dump manager functions

### PR DESCRIPTION
**Pull request by ferbncode**
Added tests for `dump_manager.py` functions. The tests fail presently. `reset_db()` fails and closes connection to the db. This needs to be fixed.

### CODE REVIEW

**Comment by paramsingh** [comment]
@brainzbot, test this please

**Comment by paramsingh** [comment]
@brainzbot, retest this please

**Comment by paramsingh** [comment]
@ferbncode, is this ready for review?

**Comment by ferbncode** [comment]
@paramsingh, yes, up for review :+1:

**Pull request merged**
