### PR TITLE
CB-305: Allow users to edit comments

### PR DESCRIPTION
**Pull request by code-master5**
Changes/additions summary:
* Separate template for comments
* Added JavaScript for dynamically displaying comment edit form when a user clicks on the comment edit button.
* Added `comment.edit` view

### CODE REVIEW

**Comment by paramsingh** [comment]
i wonder if we should wait until we integrate react and then do this over with that. This JS is not really ideal imo?

Opinions?

**Comment by code-master5** [comment]
@paramsingh You're right that the `js` is pretty messy here.

But the problem is that the `comment` section is actually a part of the `reviews` page. It would take us time to get there if we're trying to convert pages to support react. We should not wait till then to add this feature IMO. We should instead delay comments being moderatable. That's why I didn't send PR for that.

What do you think?

**Comment by code-master5** [comment]
@paramsingh @ferbncode please find some time to review and merge this (or suggest changes if any).

**Comment by code-master5** [comment]
@ferbncode @paramsingh Any reasons for not reviewing or merging this PR?

**Comment by code-master5** [comment]
comment-edit

@paramsingh  Works fine for me! Still, I've added a line break between username and comment update form. Are you sure that you [build the static files](https://critiquebrainz.readthedocs.io/intro.html#building-static-files)?

**Comment by paramsingh** [comment]
whoops

**Pull request merged**
