### PR TITLE
CB-386: Use InputRequired validator in forms instead of DataRequired

### PR DESCRIPTION
**Pull request by AbhinavOhri**
CB-386

### CODE REVIEW

**Comment by alastair** [comment]
@brainzbot add to whitelist

**Comment by alastair** [comment]
@brainzbot test this please

**Comment by alastair** [comment]
@brainzbot test this please

**Comment by alastair** [comment]
Something seems to be wrong with the tests, there's a problem where the musicbrainz database isn't being connected to. I'll look into why this isn't working

**Comment by AbhinavOhri** [comment]
@alastair In the latest build the test are working.

**Pull request merged**
