### PR TITLE
CB-351: Link external reviews imported from MusicBrainz

### PR DESCRIPTION
**Pull request by spellew**
Checks if event or release group have URL relationships of type "review," and displays the links to these reviews. Looking forward to feedback.

https://tickets.metabrainz.org/browse/CB-351

### CODE REVIEW

**Comment by reosarevok** [comment]
@brainzbot, add to whitelist

**Comment by reosarevok** [comment]
@brainzbot, test this please

**Comment by reosarevok** [comment]
@brainzbot, add to whitelist

**Comment by spellew** [comment]
Addressed pep8 warnings.

**Comment by spellew** [comment]
@ferbncode Is there an external review relationship type for places? I don't see it included here, https://musicbrainz.org/relationships/place-url.

**Comment by ferbncode** [comment]
Yup. Right. I tried this on my local machine :+1:

**Pull request merged**
