### PR TITLE
CB-374: Entity selection tabs don't change when clicked

### PR DESCRIPTION
**Pull request by amCap1712**
The current UI components need to rewritten to work correctly with Bootstrap 4. Hence, using Bootstrap 3 till then.

### CODE REVIEW

**Comment by alastair** [comment]
The latest bootstrap 3 release is 3.4.1. Why did you downgrade to 3.3?

**Comment by amCap1712** [comment]
I'll test with 3.4.1 again. I had changed it to 3.3.7 because that is what the production was on.

**Comment by alastair** [comment]
The git history of package.json shows that it was upgraded explicitly for a security upgrade, so it's not a good idea to stay with the current production version. The latest 3.x should be compatible, so I see no reason why it won't work.

**Comment by alastair** [comment]
Thanks!

**Pull request merged**
