### PR TITLE
CB-348: Add votes to dumps

### PR DESCRIPTION
**Pull request by code-master5**
Additions -
* Support for adding `vote` table contents to public dumps
* Support for importing `vote` to db from public dumps

### CODE REVIEW

**Comment by code-master5** [comment]
@paramsingh I've added tests. Please check now!

**Comment by code-master5** [comment]
@paramsingh @ferbncode please find some time to review and merge this (or suggest changes if any).

**Comment by code-master5** [comment]
@ferbncode @paramsingh Any reasons for not reviewing or merging this PR?

**Comment by paramsingh** [comment]
> @ferbncode @paramsingh Any reasons for not reviewing or merging this PR?

Been busy with irl stuff, will get to these soon.

**Pull request merged**
