### PR TITLE
CB-231: Add wrapper for fetch_multiple_places for a single MBID

### PR DESCRIPTION
**Pull request by ferbncode**
Added wrapper `_get_place_by_gid` for calling `fetch_multiple_places` for a single `MBID`.

### CODE REVIEW

**Comment by alastair** [comment]
This looks OK to me, however if there are no pages which use the multiple version, do we need the added complexity that it brings? (I seem to recall that I asked this previously, so I guess we decided to keep it)

**Comment by ferbncode** [comment]
The `/review` [pages](https://critiquebrainz.org/review) require fetching information for multiple entities. Since, these pages make a number of requests to the web-service presently, the `fetch_multiple_*` functions are added to fetch multiple entities in less time.

**Comment by alastair** [comment]
Right, I had a memory that this was the case, no problem

**Comment by gentlecat** [comment]
One thing: There's no need to mention `CB-231` since it's not directly related to this change.

**Pull request merged**
