### PR TITLE
CB-270: Implemented the reviewal of works

### PR DESCRIPTION
**Pull request by spellew**

### CODE REVIEW

**Comment by spellew** [comment]
@ferbncode Updated this pull request. Here is what the work page currently looks like.

Screenshot_2019-08-15 Halo - CritiqueBrainz

**Comment by spellew** [comment]
@ferbncode How does this look?

Screenshot_2019-08-17 Halo - CritiqueBrainz

**Comment by ferbncode** [comment]
@spellew looks good to me.

**Comment by spellew** [comment]
@ferbncode Updated the title here too.

**Pull request merged**
