### PR TITLE
CB-448: Implemented new footer design

### PR DESCRIPTION
**Pull request by phw**
Dipping my toes into the CB code :)

This implements the new footer as designed by @Aerozol in CB-448. The implementation was mostly directly taken from [Picard's website](https://picard.musicbrainz.org) as implemented in https://github.com/metabrainz/picard-website/pull/264 and adapted to the code and content of CB.

Here are some screenshots:

Front page, full width:
grafik

SM size:

grafik

XS size:

grafik

### CODE REVIEW

**Comment by Aerozol** [comment]
Screenshots look great!

**Review by MonkeyDo — COMMENTED** [review]
Thanks a lot for dipping your toes :D

As we discussed IRL, here's a couple of modifications we thought about:

1. adding a bit of padding at the bottom of the top part of the footer:
Before:
image
After:
image

2. Remove the Cover Art Archive in the fellow projects links

3. we talked about rethinking the bottom three elements ("OSS geek", MeB logo, "Found an issue") to use a flexbox layout, which would allow us to center content and reflow the elements a bit more precisely (including reordering the elements depending on screen size, instead of hiding them on small sizes)

**Comment by phw** [comment]
@MonkeyDo I finally sat down and worked on this again. The line now provides now an equal gap top and bottom and I have used a flexbox for the links below the lines. This is how it looks like at the breakpoint sizes:

**@screen-lg:**
grafik

**@screen-md:**
grafik

**@screen-sm:**
grafik

**@screen-xs:**
grafik

**Review by MonkeyDo — APPROVED** [review]
Looks great now, thanks @phw for implementing the better footer !

**Comment by MonkeyDo** [comment]
Sorry I frogot about this PR :sweat_smile:

**Pull request merged**
