### PR TITLE
CB-382: You can sometimes create a review without a revision

### PR DESCRIPTION
**Pull request by amCap1712**
It might be possible that there may be other uses or potential use case
for creating a revision in a separate transaction. Hence, added the
connection as an optional parameter. To enforce the creation in the
same transaction we can make the parameter mandatory.

JIRA: CB-382

### CODE REVIEW

**Comment by alastair** [comment]
Because a revision is only created when making a new review or updating a review, and both of them require a transaction, I don't think we need the connection parameter to be optional. I think it's fine to make it required.

**Comment by amCap1712** [comment]
Yeah, right. Makes sense. I was trying to be defensive to avoid break existing code just in case. I'll instead do a thorougher check of the code base and make the parameter required.

**Review by alastair — CHANGES_REQUESTED** [review]
marking as request changes for your further work

**Comment by amCap1712** [comment]
Something weird is happening with the tests. Running `sudo ./test.sh` leads to 5 test failures with the reason that connection to database is closed. However, running `sudo ./develop.sh test up` causes 9 tests to fail with different reasons.

**Comment by alastair** [comment]
@brainzbot test this please

**Pull request merged**
