### PR TITLE
CB-356: Implemented handling of deleted entities

### PR DESCRIPTION
**Pull request by spellew**
Set unknown_entities_for_missing flag to True for fetch_multiple_* calls

### CODE REVIEW

**Comment by spellew** [comment]
@ferbncode Tests failed due to the outdated brainzutils dependency, I'll be sure to update requirements.txt after my brainzutils pull request gets merged.

**Comment by ferbncode** [comment]
Hi @spellew, now that your PR in python-brainzutils is merged and [released](https://github.com/metabrainz/brainzutils-python/releases/tag/v1.13.0), could you also update this PR and other ones to have the latest version for brainzutils? Thanks :)

**Comment by ferbncode** [comment]
@spellew Let's update the brainzutils version here as well :)

**Comment by ferbncode** [comment]
@spellew In the unknown entities file, could you please fix and define artists for `artist_credit.artists`? Below is the exception I get while loading a unknown entity. Also, please modify the tests that you added to brainzutils for unknown entities to add includes.
```
critiquebrainz_1        | 172.28.0.1 - - [21/Aug/2019 21:46:54] "GET /release-group/c6aa40a3-479d-4a28-89e7-609816899293 HTTP/1.1" 500 -
critiquebrainz_1        | Traceback (most recent call last):
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/werkzeug/middleware/dispatcher.py", line 66, in __call__
critiquebrainz_1        |     return app(environ, start_response)
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
critiquebrainz_1        |     return self.wsgi_app(environ, start_response)
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
critiquebrainz_1        |     response = self.handle_exception(e)
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
critiquebrainz_1        |     reraise(exc_type, exc_value, tb)
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
critiquebrainz_1        |     raise value
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
critiquebrainz_1        |     response = self.full_dispatch_request()
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
critiquebrainz_1        |     rv = self.handle_user_exception(e)
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
critiquebrainz_1        |     reraise(exc_type, exc_value, tb)
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
critiquebrainz_1        |     raise value
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
critiquebrainz_1        |     rv = self.dispatch_request()
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
critiquebrainz_1        |     return view_func(**req.view_args)
critiquebrainz_1        |   File "/code/critiquebrainz/frontend/views/release_group.py", line 39, in entity
critiquebrainz_1        |     release_group = mb_release_group.get_release_group_by_id(id)
critiquebrainz_1        |   File "/code/critiquebrainz/frontend/external/musicbrainz_db/release_group.py", line 15, in get_release_group_by_id
critiquebrainz_1        |     unknown_entities_for_missing=True,
critiquebrainz_1        |   File "/usr/local/lib/python3.7/site-packages/brainzutils/musicbrainz_db/release_group.py", line 62, in fetch_multiple_release_groups
critiquebrainz_1        |     artist_credit_names = release_group.artist_credit.artists
critiquebrainz_1        | AttributeError: 'NoneType' object has no attribute 'artists'
```

**Comment by spellew** [comment]
@ferbncode I've created a brainzutils pull request to fix the unknown entities bug.

**Comment by paramsingh** [comment]
@ferbncode what's the state of this PR?

**Comment by alastair** [comment]
Replaced by https://github.com/metabrainz/critiquebrainz/pull/304

**Pull request closed without merging**
