### PR TITLE
Places Entity

### PR DESCRIPTION
**Pull request by dufferzafar**
Most of the work was done during GSoC. I've rebased the branch, and made some fixes.

The pull was open on Bitbucket but since that repo has been deleted, I am opening it here again.

### CODE REVIEW

**Comment by gentlecat** [comment]
We also have an explicit indication of entity type where they are mixed. Check pull request #26.

**Comment by gentlecat** [comment]
Looks like some imports are outdated as well:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/vagrant/fabfile.py", line 82, in test
    init_postgres(create_app().config['TEST_SQLALCHEMY_DATABASE_URI'])
  File "/vagrant/critiquebrainz/frontend/__init__.py", line 88, in create_app
    from critiquebrainz.frontend.views.place import place_bp
  File "/vagrant/critiquebrainz/frontend/views/place.py", line 4, in <module>
    from critiquebrainz.frontend.apis import musicbrainz
ImportError: No module named apis
```

**Comment by gentlecat** [comment]
Search doesn't seem to work:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 659, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask_debugtoolbar/__init__.py", line 124, in dispatch_request
    return view_func(**req.view_args)
  File "/vagrant/critiquebrainz/frontend/views/search.py", line 30, in index
    count, results = search_wrapper(query, type)
  File "/vagrant/critiquebrainz/frontend/views/search.py", line 16, in search_wrapper
    count, results = musicbrainz.search_places(query, limit=RESULTS_LIMIT, offset=offset)
  File "/vagrant/critiquebrainz/frontend/external/musicbrainz.py", line 50, in search_places
    api_resp = musicbrainzngs.search_places(query=query, limit=limit, offset=offset)
AttributeError: 'module' object has no attribute 'search_places'
```

**Comment by dufferzafar** [comment]
The search issue one is actually an upstream issue. I'll have to add search_places to mbngs. https://github.com/alastair/python-musicbrainzngs/issues/176

**Comment by gentlecat** [comment]
Please go through it again. There are still problems:
From profile page

**Pull request merged**
